model:
  name: "tide"

  n_epochs_tune: 50
  n_trials: 50
  early_stop_patience: 10
  seed: 3
  
  n_epochs_train: 80

  hp_space:
    lookback: [30, 60, 90, 180, 365]
    hidden:   [64, 128, 256, 512]
    encoder_layers: [1, 4]
    decoder_layers: [1, 4]
    decoder_dim: [16, 32, 64, 128]
    temporal_width: [2, 6]
    dropout:
      type: float
      low: 0.1
      high: 0.4
    batch: [32, 64, 128]
    lr:
      type: log_float
      low: 1.0e-4
      high: 1.0e-3
    weight_decay:
      type: log_float
      low: 1.0e-6
      high: 1.0e-4
